// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using resinBot.Core.Database;

namespace resinBot.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20201104143419_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("resinBot.Core.Database.DiscordUser", b =>
                {
                    b.Property<ulong>("DiscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastResin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResinSetTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscId");

                    b.ToTable("DiscordUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
